version: '3'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    expose:
      - 8000
    env_file:
      - backend/.env
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - ./frontend/files:/usr/share/nginx/html
      - ./backend/staticfiles:/staticfiles
      - ./backend/mediafiles:/mediafiles
    depends_on:
      - backend
    restart: unless-stopped
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .db.env
    restart: unless-stopped
