# Generated by Django 3.2.4 on 2024-11-24 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('keyword', models.CharField(max_length=50)),
                ('last_alert_sent', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('area_of_work', models.ManyToManyField(related_name='subscriptions', to='core.AreaOfWork')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('application_start_date', models.DateTimeField()),
                ('application_end_date', models.DateTimeField()),
                ('employer_description', models.TextField()),
                ('vacancy_description', models.TextField()),
                ('application_steps', models.TextField()),
                ('custom_fields', models.JSONField()),
                ('is_active', models.BooleanField()),
                ('date_posted', models.DateTimeField()),
                ('date_last_modified', models.DateTimeField()),
                ('area_of_work', models.ManyToManyField(related_name='job_postings', to='core.AreaOfWork')),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField()),
                ('alert_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emailalertsubscription')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobposting')),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='position_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='core.positiontype'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailalertsubscription',
            name='last_post_sent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobposting'),
        ),
        migrations.AddField(
            model_name='emailalertsubscription',
            name='position_type',
            field=models.ManyToManyField(related_name='subscriptions', to='core.PositionType'),
        ),
    ]
