# Generated by Django 3.2.4 on 2024-12-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jobposting_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
