# Generated by Django 3.2.4 on 2024-12-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241219_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalertsubscription',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailalertsubscription',
            name='last_post_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jobposting'),
        ),
    ]
